# Generated by Django 2.1.5 on 2019-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0002_auto_20190122_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='body',
            field=models.TextField(blank=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='template',
            name='subject',
            field=models.TextField(blank=True, verbose_name='subject'),
        ),
    ]
